### ISSUE TITLE
Various issues blocking execution of `select_and_tag_apis.ipynb` notebook

### ISSUE THREAD

**Issue by mbrukman** [google/fiddle#109]
I'm trying to run this notebook via Colab: https://colab.research.google.com/github/google/fiddle/blob/main/fiddle/examples/colabs/select_and_tag_apis.ipynb

### Issue 1: missing module

Just running it directly, I run into the first issue: missing `flax` module. The error is on this line in code under the "Running example" section:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-c74d725d96dd>](https://localhost:8080/#) in <module>
      1 from typing import Any
      2 
----> 3 from flax import linen as nn
      4 from jax import numpy as jnp
      5 

ModuleNotFoundError: No module named 'flax'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

Of course, we can include

```
!pip install flax
```

right above the first import line, so now our code will look as follows:

```
!pip install flax

from typing import Any

from flax import linen as nn
from jax import numpy as jnp
```

### Issue 2: warning about JAX version

However, when we run this cell, first we get a warning after the installation of JAX:

```
WARNING: The following packages were previously imported in this runtime:
  [jax]
You must restart the runtime in order to use newly installed versions.
```

It would be nice to select the proper version(s) of Flax, JAX, etc. that are needed for this notebook.

### Issue 3: error with `selectors.select(...).replace(...)`

Finally, the execution of the notebook fails with the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-18-029051defc8e>](https://localhost:8080/#) in <module>
      5 
      6 
----> 7 graphviz.render(experiment_config())

[<ipython-input-18-029051defc8e>](https://localhost:8080/#) in experiment_config()
      1 def experiment_config() -> fdl.Config[Sequential]:
      2   cfg = base_config()
----> 3   selectors.select(cfg, tag=ActivationDType).replace(value=jnp.int32)
      4   return cfg
      5 

AttributeError: 'Selection' object has no attribute 'replace'
```

**Comment by vufg** [comment]
Sorry for the late reply! Did you use the latest Fiddle version? Just gave it a try and it works fine. Closed this issue for now and pls let us know if you run into any other issues :)

**Comment by mbrukman** [comment]
@vufg — looks like it works for me now as well. Thanks!
