### ISSUE TITLE
Is there a way to dump a fiddle config as a nested dict?

### ISSUE THREAD

**Issue by tyler-romero** [google/fiddle#450]
Lets say I have a fiddle config that holds other fiddle configs (like in a typical modeling use case). I'm interested in dumping the outermost config to a dictionary such that the output holds the parameters and their arguments, as well as similar dictionaries for all of the nested configs (similar to pydantic v1's `.dict()`). Is this currently possible?

The use case is to improve logging, e.g. to Weights and Biases where I want to log every parameter as part of the config.

Thanks!

**Comment by vufg** [comment]
[dump_yaml()](
https://github.com/google/fiddle/blob/6651b616cc8da009a91ff8e984f3ed5514a26f00/fiddle/_src/experimental/yaml_serialization.py#L84) can print things in a flat view. The good thing is it handles custom python object well.
If you need a dict format, you could write some helper functions to transform the output of `dump_yaml` to dict. Or implementing from scratch with traversals from daglish.py.
