### ISSUE TITLE
Keep Python3.8 Support

### ISSUE THREAD

**Issue by ppwwyyxx** [google/fiddle#492]
Python3.8 support was dropped in 6651b616cc8da009a91ff8e984f3ed5514a26f00. We would really want it back.

According to https://pypistats.org/packages/jax, Python3.8 has a very large user base among jax users:
![2023-09-16_04-03](https://github.com/google/fiddle/assets/1381301/403db4a9-199c-4b30-aa00-30fcfd1b5532)

I use fiddle with PyTorch not jax, and 3.8 is still the most popular python version among its users:
![2023-09-16_04-06](https://github.com/google/fiddle/assets/1381301/531cd2ff-725e-4e2b-8cfa-65909e658780)

Although jax has dropped 3.8 support recently, the above pictures suggest that many of the ML community are using 3.8, therefore it's better if the ecosystem around it can support 3.8 for a little longer. 

@vufg

**Comment by vufg** [comment]
Thanks for bring this up! Discussing this with the team and will get back to you shortly

**Comment by vufg** [comment]
Hi there, the team agree we should continue Python 3.8 support. There are some Fiddle tests fail under python 3.8 at the moment. I'm working on the fix and will send a PR shortly.

**Comment by ppwwyyxx** [comment]
Thanks a lot!

**Comment by vufg** [comment]
added Python 3.8 support back in https://github.com/google/fiddle/commit/971eaa811f870d3b837f9f0fbf93220107068a3b. Thanks!
