### ISSUE TITLE
[Question] Push new release to PyPI

### ISSUE THREAD

**Issue by tuckerman** [google/fiddle#536]
Hi folks! We are starting to use fiddle for configuration management but ran into an issue with building generic types. This is fixed in https://github.com/google/fiddle/pull/522 but the release on PyPI is from August 2023. We built from source and things are working fine for now but could I request that a new, more recent release be created---it would simplify things a bit for us and I'm sure there are other new features/improvements that would be nice to pull in.

**Comment by keunhong** [comment]
Hi the version on PyPI still seems to be old.
